import { cn } from '@utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from '@components'
import { BookReadingProvider } from '@context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <BookReadingProvider>
        <body
          className={cn('bg-[#000000] relative text-white', inter.className)}
        >
          <header className="flex justify-center max-[500px]:w-full max-[500px]:bottom-0 max-[500px]:top-auto top-4 fixed p-2 translate-x-[-50%] left-[50%] z-40">
            <Nav />
          </header>
          {children}
        </body>
      </BookReadingProvider>
    </html>
  )
}
